---
name: Jsonlint-CI
on:
  push:
    branches:
    - main
    - develop
    - feature/**
  pull_request:
    branches:
    - main
    - develop
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    container:
      image: ixxel/unit-tests-alpine:latest
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
    - name: Jsonlint scan
      uses: ixxeL-actions/jsonlint@main
      with:
        extensions: '"json,JSON"'
        environment: '""'
        fix: 'true'
        working-dir: ./schema/accel.json
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        coverage run -m pytest  -v -s
    - name: Generate Coverage Report
      run: |
        coverage report -m
